CREATE TABLE "artists" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"name_en" text,
	"name_ja" text,
	"name_zh" text,
	"bio" text DEFAULT '',
	"bio_en" text,
	"bio_ja" text,
	"bio_zh" text,
	"birth_year" integer,
	"nationality" text,
	"specialties" text[] DEFAULT '{}'::text[],
	"awards" text[] DEFAULT '{}'::text[],
	"exhibitions" text[] DEFAULT '{}'::text[],
	"profile_image" text,
	"membership_type" text DEFAULT '준회원',
	"artist_type" text DEFAULT '일반작가',
	"title" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "artworks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"artist_id" uuid NOT NULL,
	"title" text NOT NULL,
	"title_en" text,
	"title_ja" text,
	"title_zh" text,
	"description" text DEFAULT '',
	"description_en" text,
	"category" text DEFAULT 'mixed-media',
	"style" text DEFAULT 'traditional',
	"year" integer,
	"materials" text[] DEFAULT '{}'::text[],
	"dimensions" text,
	"price" text,
	"availability" text DEFAULT 'available',
	"featured" boolean DEFAULT false,
	"tags" text[] DEFAULT '{}'::text[],
	"images" text[] DEFAULT '{}'::text[],
	"thumbnail" text,
	"condition" text,
	"technique" text,
	"authenticity_certificate" boolean DEFAULT false,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "exhibitions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"description" text DEFAULT '',
	"start_date" text NOT NULL,
	"end_date" text NOT NULL,
	"location" text,
	"venue" text,
	"curator" text,
	"featured_image_url" text,
	"gallery_images" text[] DEFAULT '{}'::text[],
	"status" text DEFAULT 'upcoming',
	"is_featured" boolean DEFAULT false,
	"is_published" boolean DEFAULT true,
	"ticket_price" integer,
	"currency" text DEFAULT 'KRW',
	"is_free" boolean DEFAULT false,
	"subtitle" text,
	"address" text,
	"max_capacity" integer,
	"admission_fee" integer,
	"opening_hours" text,
	"contact" text,
	"website" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "artworks" ADD CONSTRAINT "artworks_artist_id_artists_id_fk" FOREIGN KEY ("artist_id") REFERENCES "public"."artists"("id") ON DELETE no action ON UPDATE no action;