import { db } from '@/lib/db'
import { membershipTiers } from '@/lib/db/schema'

const tiers = [
  {
    id: 'tier-visitor',
    name: 'Visitor',
    nameKo: '방문자',
    nameEn: 'Visitor',
    nameCn: '访客',
    nameJp: '訪問者',
    description: 'Non-member website visitor',
    descriptionKo: '비회원 웹사이트 방문자',
    descriptionEn: 'Non-member website visitor',
    level: 0,
    annualFee: 0,
    color: '#9CA3AF',
    icon: 'eye',
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'tier-general',
    name: 'General Member',
    nameKo: '일반회원',
    nameEn: 'General Member',
    nameCn: '普通会员',
    nameJp: '一般会員',
    description: 'Basic membership with event access',
    descriptionKo: '기본 회원, 행사 참여 가능',
    descriptionEn: 'Basic membership with event access',
    level: 1,
    annualFee: 50000,
    color: '#6B7280',
    icon: 'user',
    sortOrder: 1,
    isActive: true,
    requirements: ['가입 신청서 제출', '연회비 납부'],
    benefits: ['전시 할인', '뉴스레터 수신', '행사 참여'],
  },
  {
    id: 'tier-student',
    name: 'Student Member',
    nameKo: '학생회원',
    nameEn: 'Student Member',
    nameCn: '学生会员',
    nameJp: '学生会員',
    description: 'Discounted membership for students',
    descriptionKo: '학생 대상 할인 회원',
    descriptionEn: 'Discounted membership for students',
    level: 1,
    annualFee: 30000,
    color: '#60A5FA',
    icon: 'graduation-cap',
    sortOrder: 2,
    isActive: true,
    requirements: ['재학증명서 제출', '연회비 납부'],
    benefits: ['전시 할인', '아카데미 수강 할인', '공모전 접수비 할인'],
  },
  {
    id: 'tier-regular',
    name: 'Regular Calligrapher',
    nameKo: '정회원 (서예가)',
    nameEn: 'Regular Calligrapher',
    nameCn: '正式会员（书法家）',
    nameJp: '正会員（書道家）',
    description: 'Verified calligrapher with exhibition rights',
    descriptionKo: '검증된 서예가, 전시 출품 자격',
    descriptionEn: 'Verified calligrapher with exhibition rights',
    level: 2,
    annualFee: 100000,
    color: '#34D399',
    icon: 'pen-tool',
    sortOrder: 3,
    isActive: true,
    requirements: ['서예 경력 3년 이상', '작품 포트폴리오 제출', '기존 회원 2인 추천'],
    benefits: ['공모전 출품 자격', '초대전 참여', '작품 판매 지원', '전시 공간 할인'],
  },
  {
    id: 'tier-invited',
    name: 'Invited Calligrapher',
    nameKo: '초대작가',
    nameEn: 'Invited Calligrapher',
    nameCn: '特邀书法家',
    nameJp: '招待作家',
    description: 'Calligrapher invited for exhibitions',
    descriptionKo: '전시 초대 자격이 있는 서예가',
    descriptionEn: 'Calligrapher invited for exhibitions',
    level: 3,
    annualFee: 150000,
    color: '#F59E0B',
    icon: 'star',
    sortOrder: 4,
    isActive: true,
    requirements: ['공모전 3회 이상 입선', '정회원 5년 이상', '심사위원 추천'],
    benefits: ['초대전 심사 없이 출품', '개인전 공간 지원', '작품집 출판 지원'],
  },
  {
    id: 'tier-recommended',
    name: 'Recommended Calligrapher',
    nameKo: '추천작가',
    nameEn: 'Recommended Calligrapher',
    nameCn: '推荐书法家',
    nameJp: '推薦作家',
    description: 'Calligrapher recommended by the board',
    descriptionKo: '이사회 추천 서예가',
    descriptionEn: 'Calligrapher recommended by the board',
    level: 4,
    annualFee: 200000,
    color: '#A78BFA',
    icon: 'award',
    sortOrder: 5,
    isActive: true,
    requirements: ['초대작가 3년 이상', '주요 공모전 수상 경력', '이사회 추천'],
    benefits: ['해외 교류전 참여', '심사위원 자격', '전시 기획 참여'],
  },
  {
    id: 'tier-judge',
    name: 'Judge / Senior Advisor',
    nameKo: '심사위원 / 고문',
    nameEn: 'Judge / Senior Advisor',
    nameCn: '评审委员 / 顾问',
    nameJp: '審査委員 / 顧問',
    description: 'Senior calligrapher serving as judge or advisor',
    descriptionKo: '공모전 심사 및 자문 역할',
    descriptionEn: 'Senior calligrapher serving as judge or advisor',
    level: 5,
    annualFee: 0,
    color: '#EF4444',
    icon: 'shield',
    sortOrder: 6,
    isActive: true,
    requirements: ['추천작가 5년 이상', '서예계 공헌도 인정'],
    benefits: ['심사위원 위촉', '명예직 부여', '해외 교류 우선 참여'],
  },
  {
    id: 'tier-director',
    name: 'Director',
    nameKo: '이사',
    nameEn: 'Director',
    nameCn: '理事',
    nameJp: '理事',
    description: 'Board of Directors member',
    descriptionKo: '이사회 구성원',
    descriptionEn: 'Board of Directors member',
    level: 6,
    annualFee: 300000,
    color: '#DC2626',
    icon: 'briefcase',
    sortOrder: 7,
    isActive: true,
    requirements: ['협회 정관에 따른 선출'],
    benefits: ['이사회 의결권', '협회 운영 참여', '대외 대표 자격'],
  },
  {
    id: 'tier-executive',
    name: 'Executive Director',
    nameKo: '상임이사 / 부이사장',
    nameEn: 'Executive Director',
    nameCn: '常务理事 / 副理事长',
    nameJp: '常任理事 / 副理事長',
    description: 'Executive board member or vice chairperson',
    descriptionKo: '상임이사 또는 부이사장',
    descriptionEn: 'Executive board member or vice chairperson',
    level: 7,
    annualFee: 500000,
    color: '#991B1B',
    icon: 'crown',
    sortOrder: 8,
    isActive: true,
    requirements: ['이사 경력 3년 이상', '이사회 선출'],
    benefits: ['상임이사회 참여', '예산 심의', '주요 사업 결정권'],
  },
  {
    id: 'tier-chairman',
    name: 'Chairperson',
    nameKo: '이사장',
    nameEn: 'Chairperson',
    nameCn: '理事长',
    nameJp: '理事長',
    description: 'Head of the association',
    descriptionKo: '협회 대표',
    descriptionEn: 'Head of the association',
    level: 8,
    annualFee: 0,
    color: '#7F1D1D',
    icon: 'gem',
    sortOrder: 9,
    isActive: true,
    requirements: ['정관에 따른 선출', '이사회 인준'],
    benefits: ['협회 최고 대표', '대외 대표권', '주요 의사결정권'],
  },
]

export async function seedMembershipTiers() {
  console.log('🌱 Seeding membership tiers...')

  for (const tier of tiers) {
    await db
      .insert(membershipTiers)
      .values(tier)
      .onConflictDoUpdate({
        target: membershipTiers.id,
        set: {
          name: tier.name,
          nameKo: tier.nameKo,
          nameEn: tier.nameEn,
          nameCn: tier.nameCn,
          nameJp: tier.nameJp,
          description: tier.description,
          descriptionKo: tier.descriptionKo,
          descriptionEn: tier.descriptionEn,
          level: tier.level,
          annualFee: tier.annualFee,
          color: tier.color,
          icon: tier.icon,
          sortOrder: tier.sortOrder,
          isActive: tier.isActive,
          requirements: tier.requirements,
          benefits: tier.benefits,
        },
      })
  }

  console.log(`✅ ${tiers.length} membership tiers seeded`)
}
