"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "ko" | "en" | "ja" | "zh"

type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  ko: {
    // Navigation
    exhibition: "전시",
    artworks: "작품",
    artists: "작가",
    events: "행사",
    catalog: "도록",
    about: "소개",
    organization: "조직",
    support: "지원",
    brand: "브랜드",
    language: "언어",
    news: "소식",
    search: "검색",
    signIn: "로그인",
    signUp: "회원가입",
    menu: "메뉴",
    
    // Exhibition submenu
    currentExhibitions: "현재 전시",
    upcomingExhibitions: "예정 전시",
    pastExhibitions: "지난 전시",
    onlineExhibitions: "온라인 전시",
    
    // Artworks submenu
    hangeulCalligraphy: "한글서예",
    hanjaCalligraphy: "한자서예",
    literatiPainting: "문인화",
    inkPainting: "수묵화",
    orientalPainting: "동양화",
    folkPainting: "민화",
    modernCalligraphy: "현대서예",
    calligraphyArt: "캘리그라피",
    sealEngraving: "전각",
    woodEngraving: "서각",
    photography: "사진",
    video: "영상",
    
    // Artists submenu
    openCallArtists: "공모작가",
    youngArtists: "청년작가",
    recommendedArtists: "추천작가",
    invitedArtists: "초대작가",
    
    // About submenu
    overview: "개요",
    regulations: "회칙",
    articles: "정관",
    operationJudging: "운영ㆍ심사",
    judgingSystem: "심사관리 시스템",
    artistSelection: "추천ㆍ초대작가 선임",
    qualifications: "자격 및 요건",
    history: "연혁",
    organizationChart: "조직도",
    brandGuidelines: "브랜드",
    
    // Events submenu
    currentEvents: "현재 행사",
    calligraphyContest2025: "2025 현장휘호 심사대회",
    calligraphyContest2024: "2024 현장휘호 심사대회",
    
    // Awards submenu
    awards: "수상작",
    awardWinners: "수상작 목록",
    awardGrades: "수상 등급",
    competitionInfo: "공모전 정보",
    
    // Award terms
    grandPrize: "대상",
    excellenceAward: "최우수상",
    meritAward: "우수상",
    fiveScriptsAward: "오체상",
    threeScriptsAward: "삼체상",
    specialSelection: "특선",
    selectedWorks: "입선",
    awardCeremony: "시상식",
    awardWinnersList: "수상자 명단",
    competitionResults: "공모전 결과",
    
    // Guide submenu (기존 News submenu)
    guide: "안내",
    notices: "공지사항",
    calligraphyLessons: "서예강좌",
    gallery: "갤러리",
    fundraising: "모금",
    shop: "SHOP",

    // Home page
    artGalleryExhibition: "동양서예협회",
    journeyThroughArts: "正法의 계승, 創新의 조화",
    aboutTitle: "소개",
    aboutText: "사단법인 동양서예협회는 正法의 계승 발전과 創新의 조화로운 구현을 통해 동양 서예 문화의 발전과 보급에 앞장서고 있습니다. 전통 서예의 정신을 현대적 감각으로 재해석하여 국내외 예술 교류를 활발히 진행하고 있습니다.",
    gallerySpace: "갤러리 공간",
    whereArtsBecome: "예술이 현실이 되는 곳",
    ourSpace: "우리의 공간",
    ourSpaceText: "서울 성북구에 위치한 동양서예협회는 서예 문화를 체험하고 학습할 수 있는 최적의 환경을 제공합니다. 전시 공간과 교육 시설을 통해 전통 서예의 깊이와 현대적 감각을 동시에 경험할 수 있습니다.",
    exhibitions: "전시회",
    ourExhibitions: "전시회",
    discoverArtistic: "예술적 세계를 발견하세요",
    ephemeralBeauty: "찰나의 아름다움",
    soulscapeAbstract: "영혼의 풍경: 추상적 표현",
    lovableEarth: "사랑스러운 지구: 예술의 선구자",
    explorationRealities: "현실의 탐구",
    globalFolkArts: "세계 민속 예술",
    infinitePerspectives: "무한한 관점",
    invitation: "초대",
    getReadyToSee: "위대한 예술을 만나볼 준비를 하세요",
    bookVisit: "방문 예약",
    ourMission: "우리의 사명",
    experienceArt: "경계를 넘어 예술을 경험하세요",
    boundaries: "경계",
    newsletter: "뉴스레터",
    subscribeNewsletter: "뉴스레터 구독하기",
    yourEmail: "이메일 주소",
    subscribe: "구독하기",

    // Footer
    current: "현재",
    upcoming: "예정",
    past: "지난",
    virtualTour: "가상 투어",
    featured: "주목할 만한",
    emerging: "신진",
    established: "기성",
    submitPortfolio: "포트폴리오 제출",
    ourStory: "우리의 이야기",
    team: "팀",
    careers: "채용",
    press: "언론 보도",
    contact: "연락처",
    faqs: "자주 묻는 질문",
    donate: "기부",
    membership: "멤버십",

    // Artworks page
    artCollection: "작품 컬렉션",
    discoverMasterpieces: "명작을 발견하세요",
    artworksDescription: "正法의 계승과 創新의 조화로 탄생한 동양 예술의 아름다움을 경험하세요",
    searchPlaceholder: "작품명, 작가명, 태그로 검색...",
    category: "카테고리",
    all: "전체",
    calligraphy: "서예",
    painting: "회화",
    sculpture: "조각",
    mixedMedia: "혼합매체",
    style: "스타일",
    traditional: "전통",
    contemporary: "현대",
    modern: "모던",
    sort: "정렬",
    sortFeatured: "추천순",
    newest: "최신순",
    popular: "인기순",
    priceLow: "가격낮은순",
    priceHigh: "가격높은순",
    available: "구매가능",
    sold: "판매완료",
    totalArtworks: "개의 작품",
    availableArtworks: "개 구매가능",
    noArtworksFound: "검색 조건에 맞는 작품이 없습니다",
    resetFilters: "필터 초기화",
    inquire: "문의하기",
    viewArtwork: "작품 보기",
    likedArtwork: "관심 작품",
    shareArtwork: "작품 공유",
    downloadImage: "이미지 다운로드",
    artworkPrice: "작품 가격",
    material: "재료",
    dimensions: "크기",
    artworkDescription: "작품설명",
    artistInfo: "작가정보",
    detailInfo: "세부정보",
    artworkCategory: "카테고리",
    artworkStyle: "스타일",
    technique: "제작기법",
    condition: "작품상태",
    certification: "진품보증",
    verified: "인증완료",
    exhibitionHistory: "전시이력",
    relatedArtworks: "관련 작품",
    otherCategories: "다른 카테고리 둘러보기",
    views: "조회",
    likes: "좋아요",
    
    // Authentication
    signOut: "로그아웃",
    profile: "프로필",
    settings: "설정",
    
    // About page
    aboutUs: "소개",
    asiaCulturalAssociation: "아시아 서예 문화 협회",
    ourVision: "우리의 비전",
    visionText: "동양 서예와 전통 예술의 아름다움을 현대에 계승하고 발전시켜, 전 세계에 동양 문화의 깊이와 가치를 전파하는 것입니다.",
    aboutMission: "우리의 사명",
    missionText: "전통 서예와 현대 예술의 조화를 통해 새로운 문화적 가치를 창조하고, 예술가들에게 창작의 기회를 제공하며, 대중에게는 동양 예술의 진정한 아름다움을 체험할 수 있는 공간을 마련합니다.",
    ourHistory: "우리의 역사",
    historyText: "1995년 설립된 아시아 서예 문화 협회는 동양 전통 서예의 보존과 발전을 위해 시작되었습니다. 지난 28년간 수많은 전시회와 문화 교류 프로그램을 통해 동서양 문화의 가교 역할을 해왔습니다.",
    ourTeam: "우리의 팀",
    directorName: "김서예",
    directorTitle: "예술 감독",
    directorBio: "동양 서예학 박사, 30년간 전통 서예 연구와 현대적 해석에 매진해온 전문가입니다.",
    curatorName: "이전시",
    curatorTitle: "큐레이터",
    curatorBio: "아시아 현대미술 전문가로, 正法의 계승과 創新의 조화를 추구하는 기획 전시를 담당합니다.",
    coordinatorName: "박문화",
    coordinatorTitle: "문화 교육 코디네이터",
    coordinatorBio: "문화 교육 프로그램 개발과 국제 교류 업무를 전담합니다.",
    contactInfo: "연락처",
    location: "위치",
    locationText: "서울특별시 중구 인사동길 12번지 전통문화센터 3층",
    phone: "전화",
    email: "이메일",
    hours: "운영시간",
    hoursText: "화요일-일요일 10:00-18:00 (월요일 휴관)",
    philosophy: "예술 철학",
    philosophyText: "붓끝에서 흘러나오는 먹의 농담은 단순한 글자가 아니라 정신과 혼이 담긴 예술입니다. 우리는 이러한 동양 서예의 정신적 가치를 현대에 되살려 새로운 예술적 표현으로 발전시켜 나가고자 합니다.",

    // Organization page
    organizationPage: "조직",
    organizationDescription: "사단법인 동양서예협회의 조직도와 임원진을 다음과 같이 소개합니다.",
    chairmanEmeritus: "명예이사장",
    advisor: "고문",
    seniorAdvisor: "상임고문",
    chairman: "이사장",
    operatingChairman: "운영위원장",
    judgeChairman: "심사위원장",
    auditor: "감사",
    standingDirector: "상임이사",
    branchDirector: "지부장",
    consultationInquiry: "상담 문의",
    consultationReservation: "상담 예약",

    // Terms of Service
    termsOfService: "이용약관",
    
    // Regulations
    regulationsTitle: "회칙",
    
    // Notice
    notice: "공지사항",
    
    // History page
    historyTitle: "연혁",
    historyDescription: "사단법인 동양서예협회의 발자취와 성과를 소개합니다.",
    contactMessage: "문의하고 싶으신 부분이 있거나 저희 협회에 남기실 말씀이 있다면 아래 연락처로 연락하여 주시기 바랍니다.",
    artistHouse: "예술가의집",
    artsCouncilKorea: "Arts Council Korea",
    exhibitionVenue: "전시 장소",
    exhibitionPeriod: "전시 기간",
    venue: "장소",
    period: "기간",
    inauguration: "취임",
    appointment: "위촉",
    generalMeeting: "총회",
    boardMeeting: "이사회",
    temporaryMeeting: "임시총회",
    regularMeeting: "정기총회",
    calligraphyContest: "휘호대회",
    appointmentCeremony: "위촉식",
    invitedArtistCertificate: "초대작가증",
    newOfficers: "신임 임원",
    corporationEstablishment: "법인 설립",
    corporationPermit: "법인 설립 허가",
    ministryOfCulture: "문화체육관광부",
    firstChairman: "초대 이사장",
    secondTerm: "제2기",
    thirdTerm: "제3기",
    koreanCalligraphyExhibition: "대한민국 동양서예대전",
    internationalCalligraphyExhibition: "한·중·일 동양서예 초대작가전",
    seoulCalligraphyMuseum: "예술의전당 서울서예박물관",
    koreaArtGallery: "인사동 한국미술관",
    culturalExchange: "문화교류",
    calligraphyAssociation: "서예협회",
    orientalCalligraphyAssociation: "동양서예협회",
    
    // Brand Guidelines
    brandGuidelinesTitle: "브랜드 가이드라인",
    brandIdentity: "브랜드 아이덴티티",
    logoIdentity: "로고 아이덴티티",
    colorPalette: "컬러 팔레트",
    tagline: "태그라인",
    slogan: "슬로건",
    
    // Catalog
    onlineCatalog: "온라인 카탈로그",
    catalogDescription: "갤러리아의 '아름다움의 순간' 전시회 카탈로그를 온라인으로 살펴보세요.",
    loadingCatalog: "카탈로그 로딩 중...",
    
    // Notice page
    importantNotice: "중요한 공지",
    generalNotice: "일반 공지",
    noticeInquiry: "공지사항 문의",
    noticeInquiryText: "공지사항에 대해 궁금한 점이 있으시면 협회 사무국으로 연락해 주세요.",
    author: "작성자",
    previous: "이전",
    next: "다음",
    
    // Exhibitions page
    currentExhibition: "현재 전시",
    ephemeralBeautyExhibition: "찰나의 아름다움 전시",
    aboutExhibition: "전시 소개",
    exhibitionText: "찰나의 아름다움 전시는 우리의 세계에서 아름다움의 일시적인 성격을 탐구합니다. 사진, 조각, 디지털 아트 등 다양한 매체를 통해 예술가들은 우리의 관심을 끌고 감정을 불러일으키는 순간적인 순간들을 반영합니다.",
    visitorGuidelines: "관람 안내",
    guidelineText1: "사진 촬영은 지정된 구역에서만 허용됩니다.",
    guidelineText2: "모든 작품으로부터 최소 1미터 거리를 유지해 주세요.",
    guidelineText3: "전시장 내에서는 음식과 음료가 금지됩니다.",
    guidelineText4: "다른 관람객을 위해 소음을 최소화해 주세요.",
    guidelineText5: "가이드 투어는 매일 오전 10시와 오후 2시에 이용 가능합니다.",
    otherExhibitions: "기타 전시",

    // Artists page
    meetVisionary: "비전을 가진 예술가들을 만나보세요",
    emmaWilliams: "엠마 윌리엄스",
    emmaText: "엠마 윌리엄스는 기술과 자연의 교차점을 탐구하는 현대 예술가입니다. 그녀의 혼합 매체 설치를 통해 점점 디지털화되는 시대에 자연 세계와의 관계를 재고하도록 관람객들을 초대합니다.",
    exploringBoundaries: "경계 탐구",
    digitalForest: "디지털 숲",
    temporalShift: "시간적 변화",
    viewProfile: "프로필 보기",
    sarahAdams: "사라 아담스",
    sarahText: "사라 아담스는 대담한 색상과 역동적인 붓놀림을 통해 감정적 풍경을 담아내는 대형 추상화로 알려져 있습니다. 그녀의 작품은 국제적으로 전시되었으며 여러 주요 컬렉션에 소장되어 있습니다.",
    emotionalTerrain: "감정적 지형",
    chromaticPulse: "색채적 맥동",
    vibrantEcho: "생생한 메아리",
    carlosDiaz: "카를로스 디아즈",
    carlosText: "카를로스 디아즈는 정체성, 기억, 문화적 유산의 주제를 탐구하는 조각가이자 설치 예술가입니다. 재활용 재료를 사용하여, 그는 관람객들이 자신의 가정을 재고하도록 도전하는 강력한 작품을 만듭니다.",
    memoryVessel: "기억의 그릇",
    culturalThreads: "문화적 실타래",
    reclaimedIdentity: "되찾은 정체성",
    takahashiYukiko: "타카하시 유키코",
    takahashiText: "타카하시 유키코는 전통적인 일본 미학과 현대 디지털 기술을 혼합한 디지털 아트와 사진작가입니다. 그녀의 몰입형 설치 작품은 명상을 초대하는 명상적 공간을 만듭니다.",
    digitalWabiSabi: "디지털 와비-사비",
    etherealGarden: "신비로운 정원",
    transientLight: "일시적인 빛",
    wilhelmCooper: "빌헬름 쿠퍼",
    wilhelmText: "빌헬름 쿠퍼는 인간의 존재와 환경 조건에 반응하는 인터랙티브 설치 작품을 만드는 사운드 아트와 조각의 교차점에서 작업합니다. 그의 작품은 공간, 소리, 인간의 인식 사이의 관계를 탐구합니다.",
    sonicField: "소닉 필드",
    resonantObjects: "공명하는 오브젝트",
    vibrationalSpace: "진동하는 공간",
    
    // 파일 관리
    fileManagement: "파일 관리",
    uploadFiles: "파일 업로드",
    fileList: "파일 목록",
    uploadImages: "이미지 업로드",
    uploadPDFs: "PDF 업로드",
    fileSize: "파일 크기",
    uploadDate: "업로드 날짜",
    fileCategory: "카테고리",
    fileTags: "태그",
    filePreview: "미리보기",
    downloadFile: "다운로드",
    copyURL: "URL 복사",
    shareFile: "공유",
    deleteFile: "삭제",
    
    // 관리자 대시보드
    dashboard: "대시보드",
    adminDashboard: "관리자 대시보드",

    // Admin/Statistics related
    totalUsers: "총 사용자 수",
    totalContent: "총 콘텐츠 수",
    monthlyStats: "월별 통계",
    artworksCount: "작품 수",
    
    // Additional specialized terms
    inkStickPreparation: "먹 준비",
    brushTechniques: "붓 기법",
    calligraphyStances: "서법 자세",
    breathingTechnique: "호흡법",
    masterStudentRelationship: "사제관계",
    traditionalTeaching: "전통 지도법",
    inkStickPreparation: "墨の準備",
    brushTechniques: "筆技",
    calligraphyStances: "書法の構え",
    breathingTechnique: "呼吸法",
    masterStudentRelationship: "師弟関係",
    traditionalTeaching: "伝統的指導",
  },
  
  en: {
    // Navigation
    exhibition: "Exhibition",
    artworks: "Artworks",
    artists: "Artists",
    events: "Events",
    catalog: "Catalog",
    about: "About",
    organization: "Organization",
    support: "Support",
    brand: "Brand",
    language: "Language",
    news: "News",
    search: "Search",
    signIn: "Sign In",
    signUp: "Sign Up",
    menu: "Menu",
    
    // Exhibition submenu
    currentExhibitions: "Current Exhibitions",
    upcomingExhibitions: "Upcoming Exhibitions",
    pastExhibitions: "Past Exhibitions",
    onlineExhibitions: "Online Exhibitions",
    
    // Artworks submenu
    hangeulCalligraphy: "Hangeul Calligraphy",
    hanjaCalligraphy: "Hanja Calligraphy",
    literatiPainting: "Literati Painting",
    inkPainting: "Ink Painting",
    orientalPainting: "Oriental Painting",
    folkPainting: "Folk Painting",
    modernCalligraphy: "Modern Calligraphy",
    calligraphyArt: "Calligraphy Art",
    sealEngraving: "Seal Engraving",
    woodEngraving: "Wood Engraving",
    photography: "Photography",
    video: "Video",
    
    // Artists submenu
    openCallArtists: "Open Call Artists",
    youngArtists: "Young Artists",
    recommendedArtists: "Recommended Artists",
    invitedArtists: "Invited Artists",
    
    // About submenu
    overview: "Overview",
    regulations: "Regulations",
    articles: "Articles of Association",
    operationJudging: "Operation & Judging",
    judgingSystem: "Judging Management System",
    artistSelection: "Recommended & Invited Artist Selection",
    qualifications: "Qualifications & Requirements",
    history: "History",
    organizationChart: "Organization Chart",
    brandGuidelines: "Brand Guidelines",
    
    // Events submenu
    currentEvents: "Current Events",
    calligraphyContest2025: "2025 On-site Calligraphy Contest",
    calligraphyContest2024: "2024 On-site Calligraphy Contest",
    
    // Awards submenu
    awards: "Awards",
    awardWinners: "Award Winners",
    awardGrades: "Award Grades",
    competitionInfo: "Competition Info",
    
    // Award terms
    grandPrize: "Grand Prize",
    excellenceAward: "Excellence Award",
    meritAward: "Merit Award",
    fiveScriptsAward: "Five Scripts Award",
    threeScriptsAward: "Three Scripts Award",
    specialSelection: "Special Selection",
    selectedWorks: "Selected Works",
    awardCeremony: "Award Ceremony",
    awardWinnersList: "Award Winners List",
    competitionResults: "Competition Results",
    
    // Guide submenu
    guide: "Guide",
    notices: "Notices",
    calligraphyLessons: "Calligraphy Lessons",
    gallery: "Gallery",
    fundraising: "Fundraising",
    shop: "SHOP",

    // Home page
    artGalleryExhibition: "Oriental Calligraphy Association",
    journeyThroughArts: "TRADITION AND MODERNITY, INCLUSION AND COMMUNICATION",
    aboutTitle: "About",
    aboutText: "The Asian Society of Calligraphic Arts (ASCA) leads the development and promotion of Oriental calligraphy culture through the harmonious implementation of tradition preservation and creative innovation. We actively promote domestic and international art exchanges by reinterpreting the spirit of traditional calligraphy with modern sensibilities.",
    gallerySpace: "Gallery Space",
    whereArtsBecome: "WHERE ARTS BECOME REALITY",
    ourSpace: "Our Space",
    ourSpaceText: "Located in Seongbuk-gu, Seoul, the Oriental Calligraphy Association provides the optimal environment for experiencing and learning calligraphy culture. Through exhibition spaces and educational facilities, you can simultaneously experience the depth of traditional calligraphy and modern sensibilities.",
    exhibitions: "Exhibitions",
    ourExhibitions: "Exhibitions",
    discoverArtistic: "DISCOVER ARTISTIC TAPESTRY",
    ephemeralBeauty: "EPHEMERAL BEAUTY",
    soulscapeAbstract: "SOULSCAPE: AN ABSTRACT PLAY",
    lovableEarth: "LOVABLE EARTH: PIONEER OF ART",
    explorationRealities: "EXPLORATION OF REALITIES",
    globalFolkArts: "GLOBAL FOLK ARTS",
    infinitePerspectives: "INFINITE PERSPECTIVES",
    invitation: "Invitation",
    getReadyToSee: "GET READY TO SEE GREAT ARTS",
    bookVisit: "Book a Visit",
    ourMission: "Our Mission",
    experienceArt: "EXPERIENCE ART BEYOND",
    boundaries: "BOUNDARIES",
    newsletter: "NEWSLETTER",
    subscribeNewsletter: "Subscribe to Newsletter",
    yourEmail: "Your email address",
    subscribe: "Subscribe",

    // Footer
    current: "Current",
    upcoming: "Upcoming",
    past: "Past",
    virtualTour: "Virtual Tour",
    featured: "Featured",
    emerging: "Emerging",
    established: "Established",
    submitPortfolio: "Submit Portfolio",
    ourStory: "Our Story",
    team: "Team",
    careers: "Careers",
    press: "Press",
    contact: "Contact",
    faqs: "FAQs",
    donate: "Donate",
    membership: "Membership",

    // Artworks page
    artCollection: "Art Collection",
    discoverMasterpieces: "Discover Masterpieces",
    artworksDescription: "Experience the beauty of Oriental art born from the harmonious implementation of tradition preservation and creative innovation",
    searchPlaceholder: "Search by artwork title, artist name, tags...",
    category: "Category",
    all: "All",
    calligraphy: "Calligraphy",
    painting: "Painting",
    sculpture: "Sculpture",
    mixedMedia: "Mixed Media",
    style: "Style",
    traditional: "Traditional",
    contemporary: "Contemporary",
    modern: "Modern",
    sort: "Sort",
    sortFeatured: "Featured",
    newest: "Newest",
    popular: "Popular",
    priceLow: "Price Low to High",
    priceHigh: "Price High to Low",
    available: "Available",
    sold: "Sold",
    totalArtworks: "artworks total",
    availableArtworks: "available",
    noArtworksFound: "No artworks found matching your criteria",
    resetFilters: "Reset Filters",
    inquire: "Inquire",
    viewArtwork: "View Artwork",
    likedArtwork: "Like Artwork",
    shareArtwork: "Share Artwork",
    downloadImage: "Download Image",
    artworkPrice: "Price",
    material: "Material",
    dimensions: "Dimensions",
    artworkDescription: "Description",
    artistInfo: "Artist Info",
    detailInfo: "Details",
    artworkCategory: "Category",
    artworkStyle: "Style",
    technique: "Technique",
    condition: "Condition",
    certification: "Authentication",
    verified: "Verified",
    exhibitionHistory: "Exhibition History",
    relatedArtworks: "Related Artworks",
    otherCategories: "Explore Other Categories",
    views: "Views",
    likes: "Likes",
    
    // Authentication
    signOut: "Sign Out",
    profile: "Profile",
    settings: "Settings",
    
    // About page
    aboutUs: "About Us",
    asiaCulturalAssociation: "Asian Society of Calligraphic Arts",
    ourVision: "Our Vision",
    visionText: "To inherit and develop the beauty of Oriental calligraphy and traditional arts in the modern era, and to spread the depth and value of Oriental culture to the world.",
    aboutMission: "Our Mission",
    missionText: "Through the harmony of traditional calligraphy and modern art, we create new cultural values, provide creative opportunities for artists, and establish spaces where the public can experience the true beauty of Oriental art.",
    ourHistory: "Our History",
    historyText: "The Asian Society of Calligraphic Arts, established in 1995, began to preserve and develop Oriental traditional calligraphy. Over the past 28 years, we have served as a bridge between Eastern and Western cultures through numerous exhibitions and cultural exchange programs.",
    ourTeam: "Our Team",
    directorName: "Kim Seo-ye",
    directorTitle: "Art Director",
    directorBio: "A specialist with a doctorate in Oriental Calligraphy who has devoted 30 years to research of traditional calligraphy and its modern interpretation.",
    curatorName: "Lee Jeon-si",
    curatorTitle: "Curator",
    curatorBio: "An expert in Asian contemporary art, responsible for planning exhibitions that pursue the harmony of tradition preservation and creative innovation.",
    coordinatorName: "Park Mun-hwa",
    coordinatorTitle: "Cultural Education Coordinator",
    coordinatorBio: "Dedicated to developing cultural education programs and international exchange work.",
    contactInfo: "Contact Information",
    location: "Location",
    locationText: "3rd Floor, Traditional Culture Center, 12 Insadong-gil, Jung-gu, Seoul",
    phone: "Phone",
    email: "Email",
    hours: "Hours",
    hoursText: "Tuesday-Sunday 10:00-18:00 (Closed Mondays)",
    philosophy: "Artistic Philosophy",
    philosophyText: "The shades of ink flowing from the brush tip are not just letters, but art containing spirit and soul. We aim to revive these spiritual values of Oriental calligraphy in the modern era and develop them into new artistic expressions.",

    // Organization page
    organizationPage: "Organization",
    organizationDescription: "We introduce the organization chart and executives of the Oriental Calligraphy Association as follows.",
    chairmanEmeritus: "Chairman Emeritus",
    advisor: "Advisor",
    seniorAdvisor: "Senior Advisor",
    chairman: "Chairman",
    operatingChairman: "Operating Chairman",
    judgeChairman: "Judge Chairman",
    auditor: "Auditor",
    standingDirector: "Standing Director",
    branchDirector: "Branch Director",
    consultationInquiry: "Consultation Inquiry",
    consultationReservation: "Consultation Reservation",

    // Terms of Service
    termsOfService: "Terms of Service",
    
    // Regulations
    regulationsTitle: "Regulations",
    
    // Notice
    notice: "Notice",
    
    // History page
    historyTitle: "History",
    historyDescription: "We introduce the footsteps and achievements of the Oriental Calligraphy Association.",
    contactMessage: "If you have any inquiries or would like to leave a message for our association, please contact us at the following address.",
    artistHouse: "Artist House",
    artsCouncilKorea: "Arts Council Korea",
    exhibitionVenue: "Exhibition Venue",
    exhibitionPeriod: "Exhibition Period",
    venue: "Venue",
    period: "Period",
    inauguration: "Inauguration",
    appointment: "Appointment",
    generalMeeting: "General Meeting",
    boardMeeting: "Board Meeting",
    temporaryMeeting: "Temporary Meeting",
    regularMeeting: "Regular Meeting",
    calligraphyContest: "Calligraphy Contest",
    appointmentCeremony: "Appointment Ceremony",
    invitedArtistCertificate: "Invited Artist Certificate",
    newOfficers: "New Officers",
    corporationEstablishment: "Corporation Establishment",
    corporationPermit: "Corporation Establishment Permit",
    ministryOfCulture: "Ministry of Culture, Sports and Tourism",
    firstChairman: "First Chairman",
    secondTerm: "Second Term",
    thirdTerm: "Third Term",
    koreanCalligraphyExhibition: "Korea Oriental Calligraphy Exhibition",
    internationalCalligraphyExhibition: "Korea-China-Japan Oriental Calligraphy Invited Artists Exhibition",
    seoulCalligraphyMuseum: "Seoul Calligraphy Museum at Seoul Arts Center",
    koreaArtGallery: "Korea Art Gallery in Insadong",
    culturalExchange: "Cultural Exchange",
    calligraphyAssociation: "Calligraphy Association",
    orientalCalligraphyAssociation: "Oriental Calligraphy Association",
    
    // Brand Guidelines
    brandGuidelinesTitle: "Brand Guidelines",
    brandIdentity: "Brand Identity",
    logoIdentity: "Logo Identity",
    colorPalette: "Color Palette",
    tagline: "Tagline",
    slogan: "Slogan",
    
    // Catalog
    onlineCatalog: "Online Catalog",
    catalogDescription: "Explore the 'Moments of Beauty' exhibition catalog from Galleria online.",
    loadingCatalog: "Loading catalog...",
    
    // Notice page
    importantNotice: "Important Notice",
    generalNotice: "General Notice",
    noticeInquiry: "Notice Inquiry",
    noticeInquiryText: "If you have any questions about the notice, please contact the association office.",
    author: "Author",
    previous: "Previous",
    next: "Next",
    
    // Exhibitions page
    currentExhibition: "Current Exhibition",
    ephemeralBeautyExhibition: "Ephemeral Beauty Exhibition",
    aboutExhibition: "About Exhibition",
    exhibitionText: "The Ephemeral Beauty exhibition explores the transient nature of beauty in our world. Through various media including photography, sculpture, and digital art, artists reflect on momentary instances that capture our attention and evoke emotions.",
    visitorGuidelines: "Visitor Guidelines",
    guidelineText1: "Photography is only allowed in designated areas.",
    guidelineText2: "Please maintain a minimum distance of 1 meter from all artworks.",
    guidelineText3: "Food and beverages are prohibited inside the exhibition hall.",
    guidelineText4: "Please minimize noise for other visitors.",
    guidelineText5: "Guided tours are available daily at 10 AM and 2 PM.",
    otherExhibitions: "Other Exhibitions",

    // Artists page
    meetVisionary: "Meet Visionary Artists",
    emmaWilliams: "Emma Williams",
    emmaText: "Emma Williams is a contemporary artist who explores the intersection of technology and nature. Through her mixed-media installations, she invites viewers to reconsider our relationship with the natural world in an increasingly digital age.",
    exploringBoundaries: "Exploring Boundaries",
    digitalForest: "Digital Forest",
    temporalShift: "Temporal Shift",
    viewProfile: "View Profile",
    sarahAdams: "Sarah Adams",
    sarahText: "Sarah Adams is known for her large-scale abstract paintings that capture emotional landscapes through bold colors and dynamic brushstrokes. Her work has been exhibited internationally and is part of several major collections.",
    emotionalTerrain: "Emotional Terrain",
    chromaticPulse: "Chromatic Pulse",
    vibrantEcho: "Vibrant Echo",
    carlosDiaz: "Carlos Diaz",
    carlosText: "Carlos Diaz is a sculptor and installation artist who explores themes of identity, memory, and cultural heritage. Using recycled materials, he creates powerful works that challenge viewers to reconsider their assumptions.",
    memoryVessel: "Memory Vessel",
    culturalThreads: "Cultural Threads",
    reclaimedIdentity: "Reclaimed Identity",
    takahashiYukiko: "Takahashi Yukiko",
    takahashiText: "Takahashi Yukiko is a digital artist and photographer who blends traditional Japanese aesthetics with contemporary digital technology. Her immersive installations create meditative spaces that invite contemplation.",
    digitalWabiSabi: "Digital Wabi-Sabi",
    etherealGarden: "Ethereal Garden",
    transientLight: "Transient Light",
    wilhelmCooper: "Wilhelm Cooper",
    wilhelmText: "Wilhelm Cooper works at the intersection of sound art and sculpture, creating interactive installations that respond to human presence and environmental conditions. His work explores the relationship between space, sound, and human perception.",
    sonicField: "Sonic Field",
    resonantObjects: "Resonant Objects",
    vibrationalSpace: "Vibrational Space",
    
    // Exhibition related additional terms
    regularExhibition: "Regular Exhibition",
    traditionalModernMeeting: "Meeting of Tradition and Modernity",
    beautyOfHangeul: "Beauty of Hangeul",
    sejongBirthday: "King Sejong's Birthday",
    commemorativeExhibition: "Commemorative Exhibition",
    youngCalligraphersInvitation: "Young Calligraphers Invitation Exhibition",
    newEraBrushTip: "New Era, New Brush Tip",
    koreachinaJapanExchange: "Korea-China-Japan Calligraphy Exchange",
    eastAsianCalligraphyMeeting: "Meeting of East Asian Calligraphy",
    worldOfSealEngraving: "World of Seal Engraving",
    stoneCarvedCharacterArt: "Art of Characters Carved in Stone",
    
    // Exhibition details
    openingHours: "Opening Hours",
    admission: "Admission",
    curator: "Curator",
    participatingArtists: "Participating Artists",
    artworksCount: "Artworks",
    highlights: "Highlights",
    hangeulSpecialSection: "Hangeul Calligraphy Special Section",
    youngArtistsModernInterpretation: "Young Artists' Modern Interpretation",
    traditionalChineseCalligraphyEssence: "Essence of Traditional Chinese Calligraphy",
    literatiPaintingCalligraphyHarmony: "Harmony of Literati Painting and Calligraphy",
    courtStyleCalligraphyEssence: "Essence of Court Style Calligraphy",
    modernHangeulCalligraphy: "Modern Hangeul Calligraphy",
    hangeulCreationPrinciple: "Hangeul Creation Principle Explanation",
    interactiveExperienceSpace: "Interactive Experience Space",
    
    // Competition/Award related
    koreanOrientalCalligraphyCompetition: "Korea Oriental Calligraphy Competition",
    competitionGuidelines: "Competition Guidelines",
    applicationForm: "Application Form",
    submissionPeriod: "Submission Period",
    judgingPeriod: "Judging Period",
    awardDetails: "Award Details",
    submissionCategories: "Submission Categories",
    hangeulSection: "Hangeul Section",
    chineseSection: "Chinese Section",
    literatiPaintingSection: "Literati Painting Section",
    regularScript: "Regular Script",
    runningScript: "Running Script",
    cursiveScript: "Cursive Script",
    clericScript: "Clerical Script",
    sealScript: "Seal Script",
    fourGentlemenPlants: "Four Gentlemen Plants",
    
    // Artist/Artwork related
    artistBio: "Artist Biography",
    artistProfile: "Artist Profile",
    artistIntroduction: "Artist Introduction",
    majorAwards: "Major Awards",
    majorExhibitions: "Major Exhibitions",
    specialties: "Specialties",
    traditionalCalligraphy: "Traditional Calligraphy",
    chineseCalligraphy: "Chinese Calligraphy",
    
    // Organization/History related
    organizationStructure: "Organization Structure",
    newOfficerAppointment: "New Officer Appointment Ceremony",
    
    // News/Notice related
    attachments: "Attachments",
    download: "Download",
    
    // Copyright policy related
    copyrightPolicy: "Copyright Policy",
    artworkProtection: "Artwork Protection",
    imageProtection: "Image Protection",
    contentProtection: "Content Protection",
    artworkCopyright: "Artwork Copyright",
    submittedExhibitedWorks: "Submitted and Exhibited Works",
    copyrightOwnership: "Copyright Ownership",
    exhibitionPromotionalUse: "Exhibition and Promotional Use",
    prohibitedUse: "Prohibited Use",
    citationMethod: "Citation Method",
    relatedLaws: "Related Laws",
    
    // File management
    fileManagement: "File Management",
    uploadFiles: "Upload Files",
    fileList: "File List",
    uploadImages: "Upload Images",
    uploadPDFs: "Upload PDFs",
    fileSize: "File Size",
    uploadDate: "Upload Date",
    fileCategory: "Category",
    fileTags: "Tags",
    filePreview: "Preview",
    downloadFile: "Download",
    copyURL: "Copy URL",
    shareFile: "Share",
    deleteFile: "Delete",
    
    // Admin dashboard
    dashboard: "Dashboard",
    adminDashboard: "Admin Dashboard",
  },
  
  ja: {
    // Navigation
    exhibition: "展示",
    artworks: "作品",
    artists: "作家",
    events: "行事",
    catalog: "図録",
    about: "紹介",
    organization: "組織",
    support: "支援",
    brand: "ブランド",
    language: "言語",
    news: "ニュース",
    search: "検索",
    signIn: "ログイン",
    signUp: "会員登録",
    menu: "メニュー",
    
    // Exhibition submenu
    currentExhibitions: "現在の展示",
    upcomingExhibitions: "予定展示",
    pastExhibitions: "過去の展示",
    onlineExhibitions: "オンライン展示",
    
    // Artworks submenu
    hangeulCalligraphy: "ハングル書道",
    hanjaCalligraphy: "漢字書道",
    literatiPainting: "文人画",
    inkPainting: "水墨画",
    orientalPainting: "東洋画",
    folkPainting: "民画",
    modernCalligraphy: "現代書道",
    calligraphyArt: "カリグラフィー",
    sealEngraving: "篆刻",
    woodEngraving: "書刻",
    photography: "写真",
    video: "映像",
    
    // Artists submenu
    openCallArtists: "公募作家",
    youngArtists: "青年作家",
    recommendedArtists: "推薦作家",
    invitedArtists: "招待作家",
    
    // About submenu
    overview: "概要",
    regulations: "規定",
    articles: "定款",
    operationJudging: "運営・審査",
    judgingSystem: "審査管理システム",
    artistSelection: "推薦・招待作家選任",
    qualifications: "資格及び要件",
    history: "沿革",
    organizationChart: "組織図",
    brandGuidelines: "ブランド",
    
    // Events submenu
    currentEvents: "現在の行事",
    calligraphyContest2025: "2025現場揮毫審査大会",
    calligraphyContest2024: "2024現場揮毫審査大会",
    
    // Awards submenu
    awards: "受賞作",
    awardWinners: "受賞者一覧",
    awardGrades: "受賞等級",
    competitionInfo: "コンペティション情報",
    
    // Award terms
    grandPrize: "大賞",
    excellenceAward: "最優秀賞",
    meritAward: "優秀賞",
    fiveScriptsAward: "五体賞",
    threeScriptsAward: "三体賞",
    specialSelection: "特選",
    selectedWorks: "入選",
    awardCeremony: "授賞式",
    awardWinnersList: "受賞者一覧",
    competitionResults: "コンペティション結果",
    
    // 전시회 관련 추가
    regularExhibition: "定期展",
    traditionalModernMeeting: "伝統と現代の出会い",
    beautyOfHangeul: "ハングルの美しさ",
    sejongBirthday: "世宗大王誕生",
    commemorativeExhibition: "記念展",
    youngCalligraphersInvitation: "青年書家招待展",
    newEraBrushTip: "新時代、新しい筆先",
    koreachinaJapanExchange: "韓中日書道交流展",
    eastAsianCalligraphyMeeting: "東アジア書道の出会い",
    worldOfSealEngraving: "篆刻の世界",
    stoneCarvedCharacterArt: "石に刻まれた文字の芸術",
    
    // 전시 상세 정보
    venue: "会場",
    period: "期間",
    openingHours: "開館時間",
    admission: "入場料",
    curator: "キュレーター",
    participatingArtists: "参加作家",
    artworksCount: "作品数",
    highlights: "ハイライト",
    hangeulSpecialSection: "ハングル書道特別セクション",
    youngArtistsModernInterpretation: "若い作家たちの現代的解釈",
    traditionalChineseCalligraphyEssence: "伝統漢字書道の精髄",
    literatiPaintingCalligraphyHarmony: "文人画と書道の調和",
    courtStyleCalligraphyEssence: "宮体書道の精髄",
    modernHangeulCalligraphy: "現代ハングル書道",
    hangeulCreationPrinciple: "ハングル創製原理の解説",
    interactiveExperienceSpace: "インタラクティブ体験空間",
    
    // 공모전/수상 관련
    koreanOrientalCalligraphyCompetition: "大韓民国東洋書道大展",
    competitionGuidelines: "公募要綱",
    applicationForm: "申請書",
    submissionPeriod: "応募期間",
    judgingPeriod: "審査期間",
    awardDetails: "賞詳細",
    submissionCategories: "応募部門",
    hangeulSection: "ハングル部門",
    chineseSection: "漢文部門",
    literatiPaintingSection: "文人画部門",
    regularScript: "楷書",
    runningScript: "行書",
    cursiveScript: "草書",
    clericScript: "隷書",
    sealScript: "篆書",
    fourGentlemenPlants: "梅蘭菊竹",
    
    // 작가/작품 관련
    artistBio: "作家略歴",
    artistProfile: "作家プロフィール",
    artistIntroduction: "作家紹介",
    majorAwards: "主要受賞歴",
    majorExhibitions: "主要展示",
    specialties: "専門分野",
    traditionalCalligraphy: "伝統書道",
    modernCalligraphy: "現代書道",
    chineseCalligraphy: "漢文書道",
    hangeulCalligraphy: "ハングル書道",
    literatiPainting: "文人画",
    inkPainting: "水墨画",
    folkPainting: "民画",
    orientalPainting: "東洋画",
    woodEngraving: "書刻",
    
    // 조직/연혁 관련
    organizationStructure: "組織構造",
    organizationDescription: "社団法人東洋書道協会の組織図と役員を以下のように紹介いたします",
    consultationInquiry: "相談問い合わせ",
    consultationReservation: "相談予約",
    newOfficerAppointment: "新任役員委嘱式",
    regularMeeting: "定期総会",
    temporaryMeeting: "臨時総会",
    boardMeeting: "理事会",
    inauguration: "就任",
    
    // 소식/공지 관련
    attachments: "添付ファイル",
    download: "ダウンロード",
    
    // 저작권 정책 관련
    copyrightPolicy: "著作権ポリシー",
    artworkProtection: "作品保護",
    imageProtection: "画像保護",
    contentProtection: "コンテンツ保護",
    artworkCopyright: "作品著作権",
    submittedExhibitedWorks: "提出及び展示作品",
    copyrightOwnership: "著作権所有",
    exhibitionPromotionalUse: "展示及び宣伝用使用",
    prohibitedUse: "使用禁止",
    citationMethod: "引用方法",
    relatedLaws: "関連法令",
    
    // 파일 관리
    fileManagement: "ファイル管理",
    uploadFiles: "ファイルアップロード",
    fileList: "ファイルリスト",
    uploadImages: "画像アップロード",
    uploadPDFs: "PDFアップロード",
    fileSize: "ファイルサイズ",
    uploadDate: "アップロード日",
    fileCategory: "カテゴリー",
    fileTags: "タグ",
    filePreview: "プレビュー",
    downloadFile: "ダウンロード",
    copyURL: "URLコピー",
    shareFile: "共有",
    deleteFile: "削除",
    
    // 관리자 ダッシュボード
    dashboard: "ダッシュボード",
    adminDashboard: "管理者ダッシュボード",
  },
  
  zh: {
    // Navigation
    exhibition: "展览",
    artworks: "艺术品",
    artists: "艺术家",
    events: "活动",
    catalog: "目录",
    about: "关于",
    organization: "组织",
    support: "支持",
    brand: "品牌",
    language: "语言",
    news: "新闻",
    search: "搜索",
    signIn: "登录",
    signUp: "注册",
    menu: "菜单",
    
    // Exhibition submenu
    currentExhibitions: "当前展览",
    upcomingExhibitions: "即将举办的展览",
    pastExhibitions: "过去的展览",
    onlineExhibitions: "在线展览",
    
    // Artworks submenu
    hangeulCalligraphy: "韩文书法",
    hanjaCalligraphy: "汉字书法",
    literatiPainting: "文人画",
    inkPainting: "水墨画",
    orientalPainting: "东方画",
    folkPainting: "民画",
    modernCalligraphy: "现代书法",
    calligraphyArt: "书法艺术",
    sealEngraving: "篆刻",
    woodEngraving: "书刻",
    photography: "摄影",
    video: "视频",
    
    // Artists submenu
    openCallArtists: "公开征集艺术家",
    youngArtists: "青年艺术家",
    recommendedArtists: "推荐艺术家",
    invitedArtists: "邀请艺术家",
    
    // About submenu
    overview: "概述",
    regulations: "规定",
    articles: "章程",
    operationJudging: "运营·审查",
    judgingSystem: "审查管理系统",
    artistSelection: "推荐·邀请作家选任",
    qualifications: "资格及要求",
    history: "历史",
    organizationChart: "组织图",
    brandGuidelines: "品牌指南",
    
    // Events submenu
    currentEvents: "当前活动",
    calligraphyContest2025: "2025年现场挥毫审查大赛",
    calligraphyContest2024: "2024年现场挥毫审查大赛",
    
    // Awards submenu
    awards: "获奖作品",
    awardWinners: "获奖者名单",
    awardGrades: "获奖等级",
    competitionInfo: "比赛信息",
    
    // Award terms
    grandPrize: "大奖",
    excellenceAward: "最优秀奖",
    meritAward: "优秀奖",
    fiveScriptsAward: "五体奖",
    threeScriptsAward: "三体奖",
    specialSelection: "特选",
    selectedWorks: "入选",
    awardCeremony: "颁奖典礼",
    awardWinnersList: "获奖者名单",
    competitionResults: "比赛结果",
    
    // 전시회 관련 추가
    regularExhibition: "定期展",
    traditionalModernMeeting: "传统与现代的邂逅",
    beautyOfHangeul: "韩文的美丽",
    sejongBirthday: "世宗大王诞辰",
    commemorativeExhibition: "纪念展",
    youngCalligraphersInvitation: "青年书法家邀请展",
    newEraBrushTip: "新时代，新笔尖",
    koreachinaJapanExchange: "韩中日书法交流展",
    eastAsianCalligraphyMeeting: "东亚书法的汇聚",
    worldOfSealEngraving: "篆刻的世界",
    stoneCarvedCharacterArt: "石上雕刻的文字艺术",
    
    // 전시 상세 정보
    venue: "场所",
    period: "期间",
    openingHours: "开放时间",
    admission: "入场费",
    curator: "策展人",
    participatingArtists: "参展艺术家",
    artworksCount: "作品数",
    highlights: "亮点",
    hangeulSpecialSection: "韩文书法特别展区",
    youngArtistsModernInterpretation: "年轻艺术家的现代诠释",
    traditionalChineseCalligraphyEssence: "传统汉字书法的精髓",
    literatiPaintingCalligraphyHarmony: "文人画与书法的和谐",
    courtStyleCalligraphyEssence: "宫体书法的精髓",
    modernHangeulCalligraphy: "现代韩文书法",
    hangeulCreationPrinciple: "韩文创制原理解说",
    interactiveExperienceSpace: "互动体验空间",
    
    // 공모전/수상 관련
    koreanOrientalCalligraphyCompetition: "大韩民国东方书法大展",
    competitionGuidelines: "公募要项",
    applicationForm: "申请书",
    submissionPeriod: "征集期间",
    judgingPeriod: "审查期间",
    awardDetails: "奖项详情",
    submissionCategories: "征集部门",
    hangeulSection: "韩文部门",
    chineseSection: "汉文部门",
    literatiPaintingSection: "文人画部门",
    regularScript: "楷书",
    runningScript: "行书",
    cursiveScript: "草书",
    clericScript: "隶书",
    sealScript: "篆书",
    fourGentlemenPlants: "梅兰菊竹",
    
    // 작가/작품 관련
    artistBio: "艺术家简历",
    artistProfile: "艺术家档案",
    artistIntroduction: "艺术家介绍",
    majorAwards: "主要获奖经历",
    majorExhibitions: "主要展览",
    specialties: "专业领域",
    traditionalCalligraphy: "传统书法",
    modernCalligraphy: "现代书法",
    chineseCalligraphy: "汉文书法",
    hangeulCalligraphy: "韩文书法",
    literatiPainting: "文人画",
    inkPainting: "水墨画",
    folkPainting: "民画",
    orientalPainting: "东方画",
    woodEngraving: "书刻",
    
    // 조직/연혁 관련
    organizationStructure: "组织结构",
    organizationDescription: "社团法人东方书法协会的组织图和高管介绍如下",
    consultationInquiry: "咨询问询",
    consultationReservation: "咨询预约",
    newOfficerAppointment: "新任高管委任式",
    regularMeeting: "定期总会",
    temporaryMeeting: "临时总会",
    boardMeeting: "理事会",
    inauguration: "就任",
    
    // 소식/공지 관련
    attachments: "添付ファイル",
    download: "ダウンロード",
    
    // 저작권 정책 관련
    copyrightPolicy: "著作権ポリシー",
    artworkProtection: "作品保護",
    imageProtection: "画像保護",
    contentProtection: "コンテンツ保護",
    artworkCopyright: "作品著作権",
    submittedExhibitedWorks: "提出及び展示作品",
    copyrightOwnership: "著作権所有",
    exhibitionPromotionalUse: "展示及び宣伝用使用",
    prohibitedUse: "使用禁止",
    citationMethod: "引用方法",
    relatedLaws: "関連法令",
    
    // 파일 관리
    fileManagement: "ファイル管理",
    uploadFiles: "ファイルアップロード",
    fileList: "ファイルリスト",
    uploadImages: "画像アップロード",
    uploadPDFs: "PDFアップロード",
    fileSize: "ファイルサイズ",
    uploadDate: "アップロード日",
    fileCategory: "カテゴリー",
    fileTags: "タグ",
    filePreview: "プレビュー",
    downloadFile: "ダウンロード",
    copyURL: "URLコピー",
    shareFile: "共有",
    deleteFile: "削除",
    
    // 관리자 ダッシュボード
    dashboard: "ダッシュボード",
    adminDashboard: "管理者ダッシュボード",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("ko")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && ["ko", "en", "ja", "zh"].includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  useEffect(() => {
    localStorage.setItem("language", language)
    document.documentElement.lang = language
  }, [language])

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
