import type {
  MemberProfile,
  MembershipDashboardStats,
  MembershipTierInfo,
} from '@/lib/types/membership'

export const mockStats: MembershipDashboardStats = {
  totalMembers: 1247,
  membersByTier: {
    1: 523,
    2: 412,
    3: 198,
    4: 67,
    5: 32,
    6: 15,
  },
  membersByStatus: {
    active: 1156,
    pending_approval: 67,
    inactive: 18,
    suspended: 6,
  },
  newMembersThisMonth: 43,
  pendingApplications: 23,
  activePrograms: 8,
  upcomingEvents: 12,
  revenueThisMonth: 8450000,
  memberRetentionRate: 94.2,
  averageProfileCompleteness: 78,
}

export const membershipTiers: MembershipTierInfo[] = [
  {
    id: '1',
    name: 'student',
    nameKo: '학생 회원',
    nameEn: 'Student Member',
    level: 1,
    color: '#10B981',
    icon: '📚',
    annualFee: 50000,
    currency: 'KRW',
    requirements: JSON.stringify([]),
    benefits: JSON.stringify([]),
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
    sortOrder: 1,
  },
  {
    id: '2',
    name: 'advanced',
    nameKo: '고급 실습생',
    nameEn: 'Advanced Practitioner',
    level: 2,
    color: '#3B82F6',
    icon: '🎨',
    annualFee: 100000,
    currency: 'KRW',
    requirements: JSON.stringify([]),
    benefits: JSON.stringify([]),
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
    sortOrder: 2,
  },
  {
    id: '3',
    name: 'certified',
    nameKo: '인증 서예가',
    nameEn: 'Certified Master',
    level: 3,
    color: '#8B5CF6',
    icon: '🏆',
    annualFee: 200000,
    currency: 'KRW',
    requirements: JSON.stringify([]),
    benefits: JSON.stringify([]),
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
    sortOrder: 3,
  },
  {
    id: '4',
    name: 'honorary',
    nameKo: '명예 서예가',
    nameEn: 'Honorary Master',
    level: 4,
    color: '#F59E0B',
    icon: '👑',
    annualFee: 0,
    currency: 'KRW',
    requirements: JSON.stringify([]),
    benefits: JSON.stringify([]),
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
    sortOrder: 4,
  },
  {
    id: '5',
    name: 'institutional',
    nameKo: '기관 회원',
    nameEn: 'Institutional Member',
    level: 5,
    color: '#EF4444',
    icon: '🏛️',
    annualFee: 500000,
    currency: 'KRW',
    requirements: JSON.stringify([]),
    benefits: JSON.stringify([]),
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
    sortOrder: 5,
  },
  {
    id: '6',
    name: 'international',
    nameKo: '국제 회원',
    nameEn: 'International Associate',
    level: 6,
    color: '#14B8A6',
    icon: '🌏',
    annualFee: 150000,
    currency: 'KRW',
    requirements: JSON.stringify([]),
    benefits: JSON.stringify([]),
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
    sortOrder: 6,
  },
]

export const mockMembers: (MemberProfile & { user?: any })[] = [
  {
    id: '1',
    userId: 'user1',
    membershipNumber: 'ASCA-2025-001',
    tierLevel: 3,
    tierId: '3',
    status: 'active',
    joinDate: new Date('2023-01-15'),
    fullName: '김서예',
    fullNameKo: '김서예',
    fullNameEn: 'Kim Seo-ye',
    nationality: 'KR',
    phoneNumber: '010-1234-5678',
    calligraphyExperience: 12,
    specializations: JSON.stringify([]),
    preferredStyles: JSON.stringify([]),
    teachingExperience: 5,
    certifications: JSON.stringify([]),
    achievements: JSON.stringify([]),
    emergencyContactName: '',
    emergencyContactPhone: '',
    address: '',
    country: 'KR',
    educationBackground: JSON.stringify({ general: [], calligraphy: [] }),
    interests: JSON.stringify([]),
    languages: JSON.stringify(['ko', 'en']),
    membershipHistory: JSON.stringify([]),
    paymentHistory: JSON.stringify([]),
    privacySettings: JSON.stringify({
      profileVisibility: 'members_only',
      contactInfoVisible: false,
      achievementsVisible: true,
      participationHistoryVisible: true,
      allowDirectMessages: true,
      showOnlinStatus: false,
    }),
    participationScore: 450,
    contributionScore: 120,
    profileCompleteness: 95,
    marketingConsent: true,
    dataProcessingConsent: true,
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2025-01-20'),
    user: {
      email: 'kim.seoye@example.com',
      avatar: '/images/artists/kangdaehee.avif',
    },
  },
  {
    id: '2',
    userId: 'user2',
    membershipNumber: 'ASCA-2025-002',
    tierLevel: 2,
    tierId: '2',
    status: 'active',
    joinDate: new Date('2023-03-20'),
    fullName: '이묵향',
    fullNameKo: '이묵향',
    fullNameEn: 'Lee Muk-hyang',
    nationality: 'KR',
    phoneNumber: '010-2345-6789',
    calligraphyExperience: 8,
    specializations: JSON.stringify([]),
    preferredStyles: JSON.stringify([]),
    teachingExperience: 3,
    certifications: JSON.stringify([]),
    achievements: JSON.stringify([]),
    emergencyContactName: '',
    emergencyContactPhone: '',
    address: '',
    country: 'KR',
    educationBackground: JSON.stringify({ general: [], calligraphy: [] }),
    interests: JSON.stringify([]),
    languages: JSON.stringify(['ko']),
    membershipHistory: JSON.stringify([]),
    paymentHistory: JSON.stringify([]),
    privacySettings: JSON.stringify({
      profileVisibility: 'members_only',
      contactInfoVisible: false,
      achievementsVisible: true,
      participationHistoryVisible: true,
      allowDirectMessages: true,
      showOnlinStatus: false,
    }),
    participationScore: 320,
    contributionScore: 85,
    profileCompleteness: 78,
    marketingConsent: false,
    dataProcessingConsent: true,
    createdAt: new Date('2023-03-20'),
    updatedAt: new Date('2025-01-19'),
    user: {
      email: 'lee.mukhyang@example.com',
      avatar: '/images/artists/sojeonga.avif',
    },
  },
]
