import type { Artwork } from './artwork-types'

export const sampleArtworks: Artwork[] = [
  {
    id: '1',
    title: '산수화 - 봄의 선율',
    titleEn: 'Landscape - Spring Melody',
    titleJa: '山水画 - 春のメロディー',
    titleZh: '山水画 - 春天的旋律',
    artist: '김한수',
    artistEn: 'Kim Han-su',
    artistJa: 'キム・ハンス',
    artistZh: '金汉水',
    category: '수묵화',
    style: '전통',
    medium: '종이에 수묵',
    mediumEn: 'Ink on Paper',
    dimensions: '60 × 80 cm',
    year: 2023,
    price: 1200000,
    currency: 'KRW',
    description:
      '전통 산수화 기법으로 표현한 봄의 아름다운 풍경입니다. 작가는 자연의 생명력과 계절의 변화를 섬세한 붓터치로 담아냈습니다. 화면 전체에 흐르는 조화로운 구성과 깊이 있는 먹색의 농담 변화가 인상적입니다.',
    descriptionEn:
      'Beautiful spring landscape expressed with traditional landscape painting techniques. The artist captured the vitality of nature and seasonal changes with delicate brushstrokes.',
    descriptionJa:
      '伝統的な山水画技法で表現した春の美しい風景です。作家は自然の生命力と季節の変化を繊細な筆のタッチで込めました。',
    descriptionZh:
      '用传统山水画技法表现的春天美丽风景。艺术家用细腻的笔触捕捉了自然的生命力和季节的变化。',
    imageUrl: '/images/artworks/hwangjeguk-chode.avif',
    images: [
      '/images/artworks/hwangjeguk-chode.avif',
      '/images/artworks/choinanju-chode.avif',
      '/images/artworks/limhyeongi-chode.avif',
    ],
    isAvailable: true,
    isFeatured: true,
    tags: ['봄', '산수', '전통', '수묵'],
    views: 156,
    likes: 23,
    artistBio:
      '김한수는 30년 경력의 전통 산수화 전문가로, 동양화 특유의 정신세계를 현대적 감각으로 재해석하는 작업을 지속하고 있습니다.',
    technique: '전통 수묵화법, 선염기법, 점묘법',
    provenance: '작가 작업실, 개인 컬렉션',
    exhibition: '2023 봄 풍경전, 서울 갤러리',
    condition: '최상급 (작가 보관)',
    certification: true,
    artistId: '1',
    weight: '0.5kg',
    materials: ['한지', '먹', '안료'],
    significance: '작가의 대표작 중 하나로, 전통 산수화의 현대적 해석을 보여주는 중요한 작품',
    collectionHistory: '2023년 작가 작업실에서 직접 구입',
  },
  {
    id: '2',
    title: '한자서예 - 묵향',
    titleEn: 'Chinese Calligraphy - Ink Fragrance',
    titleJa: '漢字書道 - 墨香',
    titleZh: '汉字书法 - 墨香',
    artist: '이정화',
    artistEn: 'Lee Jung-hwa',
    artistJa: 'イ・ジョンファ',
    artistZh: '李静华',
    category: '한자서예',
    style: '전통',
    font: '행서',
    paperSize: '반절지(35×135cm)',
    medium: '한지에 먹',
    mediumEn: 'Ink on Hanji',
    dimensions: '35 × 135 cm',
    year: 2024,
    price: 800000,
    currency: 'KRW',
    description: '현대적 감각으로 재해석한 전통 서예 작품입니다.',
    descriptionEn: 'Traditional calligraphy reinterpreted with modern sensibility.',
    descriptionJa: '現代的感覚で再解釈した伝統書道作品です。',
    descriptionZh: '用现代感觉重新诠释的传统书法作品。',
    imageUrl: '/images/artworks/joyeongrang-chode.avif',
    images: ['/images/artworks/joyeongrang-chode.avif'],
    isAvailable: true,
    isFeatured: false,
    tags: ['서예', '현대', '먹향'],
    views: 89,
    likes: 12,
    artistBio: '이정화는 현대 서예의 새로운 지평을 열어가는 작가입니다.',
    technique: '현대 서예기법',
    condition: '우수',
    certification: false,
    artistId: '2',
  },
  {
    id: '3',
    title: '한글서예 - 사랑',
    titleEn: 'Korean Calligraphy - Love',
    titleJa: 'ハングル書道 - 愛',
    titleZh: '韩文书法 - 爱',
    artist: '박서예',
    artistEn: 'Park Seo-ye',
    artistJa: 'パク・ソイェ',
    artistZh: '朴书艺',
    category: '한글서예',
    style: '전통',
    font: '궁채',
    paperSize: '기타',
    medium: '한지에 먹',
    mediumEn: 'Ink on Hanji',
    dimensions: '50 × 70 cm',
    year: 2023,
    price: 600000,
    currency: 'KRW',
    description: '한글의 아름다움을 전통 서예 기법으로 표현한 작품입니다.',
    descriptionEn:
      'A work expressing the beauty of Hangeul with traditional calligraphy techniques.',
    descriptionJa: 'ハングルの美しさを伝統書道技法で表現した作品です。',
    descriptionZh: '用传统书法技法表现韩文之美的作品。',
    imageUrl: '/images/artworks/minmunja-hancho.avif',
    images: ['/images/artworks/minmunja-hancho.avif'],
    isAvailable: true,
    isFeatured: false,
    tags: ['한글', '서예', '전통'],
    views: 78,
    likes: 15,
    condition: '최상급',
    certification: true,
    artistId: '3',
  },
  {
    id: '4',
    title: '민화 - 모란도',
    titleEn: 'Folk Painting - Peony',
    titleJa: '民画 - 牡丹図',
    titleZh: '民画 - 牡丹图',
    artist: '최민화',
    artistEn: 'Choi Min-hwa',
    artistJa: 'チェ・ミンファ',
    artistZh: '崔民画',
    category: '민화',
    style: '전통',
    medium: '비단에 채색',
    mediumEn: 'Color on Silk',
    dimensions: '40 × 60 cm',
    year: 2024,
    price: 900000,
    currency: 'KRW',
    description:
      '전통 민화 기법으로 그린 모란꽃 그림입니다. 부귀영화를 상징하는 모란의 화려함을 섬세하게 표현했습니다.',
    descriptionEn: 'A peony painting drawn with traditional folk painting techniques.',
    descriptionJa: '伝統民画技法で描いた牡丹の絵です。',
    descriptionZh: '用传统民画技法绘制的牡丹花画。',
    imageUrl: '/images/artworks/sojeonga-hancho.avif',
    images: ['/images/artworks/sojeonga-hancho.avif'],
    isAvailable: true,
    isFeatured: true,
    tags: ['민화', '모란', '전통', '채색'],
    views: 124,
    likes: 28,
    condition: '최상급',
    certification: true,
    artistId: '4',
  },
  {
    id: '5',
    title: '캘리그라피 - 희망',
    titleEn: 'Calligraphy - Hope',
    titleJa: 'カリグラフィー - 希望',
    titleZh: '书法艺术 - 希望',
    artist: '김현대',
    artistEn: 'Kim Hyun-dae',
    artistJa: 'キム・ヒョンデ',
    artistZh: '金现代',
    category: '캘리그라피',
    style: '현대',
    medium: '캔버스에 아크릴',
    mediumEn: 'Acrylic on Canvas',
    dimensions: '80 × 100 cm',
    year: 2024,
    price: 1500000,
    currency: 'KRW',
    description:
      '현대적 감각으로 재해석한 캘리그라피 작품입니다. 희망이라는 단어를 역동적이고 현대적인 표현으로 담아냈습니다.',
    descriptionEn: 'A calligraphy work reinterpreted with modern sensibility.',
    descriptionJa: '現代的感覚で再解釈したカリグラフィー作品です。',
    descriptionZh: '用现代感觉重新诠释的书法艺术作品。',
    imageUrl: '/images/artworks/sojeonga-chode.avif',
    images: ['/images/artworks/sojeonga-chode.avif'],
    isAvailable: true,
    isFeatured: false,
    tags: ['캘리그라피', '현대', '희망', '아크릴'],
    views: 95,
    likes: 18,
    condition: '최상급',
    certification: false,
    artistId: '5',
  },
  {
    id: '6',
    title: '한자서예 - 해서체',
    titleEn: 'Chinese Calligraphy - Regular Script',
    titleJa: '漢字書道 - 楷書',
    titleZh: '汉字书法 - 楷书',
    artist: '정해서',
    artistEn: 'Jung Hae-seo',
    artistJa: 'ジョン・ヘソ',
    artistZh: '郑楷书',
    category: '한자서예',
    style: '전통',
    font: '해서',
    paperSize: '기타',
    medium: '한지에 먹',
    mediumEn: 'Ink on Hanji',
    dimensions: '45 × 65 cm',
    year: 2023,
    price: 750000,
    currency: 'KRW',
    description:
      '정통 해서체로 쓴 한자 서예 작품입니다. 단정하고 균형 잡힌 글자 형태가 특징입니다.',
    descriptionEn: 'Chinese calligraphy written in authentic regular script.',
    descriptionJa: '正統楷書で書いた漢字書道作品です。',
    descriptionZh: '用正统楷书书写的汉字书法作品。',
    imageUrl: '/images/artworks/contest-cover.avif',
    images: ['/images/artworks/contest-cover.avif'],
    isAvailable: true,
    isFeatured: false,
    tags: ['한자서예', '해서', '전통'],
    views: 67,
    likes: 11,
    condition: '최상급',
    certification: true,
    artistId: '6',
  },
  {
    id: '7',
    title: '한글서예 - 흘림체',
    titleEn: 'Korean Calligraphy - Cursive Style',
    titleJa: 'ハングル書道 - 草書体',
    titleZh: '韩文书法 - 草书体',
    artist: '김흘림',
    artistEn: 'Kim Heul-lim',
    artistJa: 'キム・フルリム',
    artistZh: '金草书',
    category: '한글서예',
    style: '전통',
    font: '흘림체',
    paperSize: '기타',
    medium: '한지에 먹',
    mediumEn: 'Ink on Hanji',
    dimensions: '60 × 80 cm',
    year: 2024,
    price: 850000,
    currency: 'KRW',
    description:
      '한글 흘림체의 유려한 아름다움을 보여주는 작품입니다. 자연스러운 필획의 흐름이 인상적입니다.',
    descriptionEn: 'A work showing the graceful beauty of Korean cursive calligraphy.',
    descriptionJa: 'ハングル草書体の流麗な美しさを見せる作品です。',
    descriptionZh: '展现韩文草书体优美之美的作品。',
    imageUrl: '/images/artworks/contest-page5.avif',
    images: ['/images/artworks/contest-page5.avif'],
    isAvailable: true,
    isFeatured: true,
    tags: ['한글서예', '흘림체', '전통', '유려함'],
    views: 142,
    likes: 31,
    condition: '최상급',
    certification: true,
    artistId: '7',
  },
  {
    id: '8',
    title: '한자서예 - 전서체',
    titleEn: 'Chinese Calligraphy - Seal Script',
    titleJa: '漢字書道 - 篆書',
    titleZh: '汉字书法 - 篆书',
    artist: '이전서',
    artistEn: 'Lee Jeon-seo',
    artistJa: 'イ・ジョンソ',
    artistZh: '李篆书',
    category: '한자서예',
    style: '전통',
    font: '전서',
    paperSize: '전지(70×135cm)',
    medium: '한지에 먹',
    mediumEn: 'Ink on Hanji',
    dimensions: '70 × 135 cm',
    year: 2023,
    price: 950000,
    currency: 'KRW',
    description:
      '고대 전서체의 고풍스러운 멋을 현대에 재현한 작품입니다. 장중하고 위엄 있는 글자체가 특징입니다.',
    descriptionEn:
      'A work that recreates the antique charm of ancient seal script in modern times.',
    descriptionJa: '古代篆書の古風な趣を現代に再現した作品です。',
    descriptionZh: '在现代重现古代篆书古朴韵味的作品。',
    imageUrl: '/images/artworks/nakjiron-baeogyeong.avif',
    images: ['/images/artworks/nakjiron-baeogyeong.avif'],
    isAvailable: true,
    isFeatured: false,
    tags: ['한자서예', '전서', '전통', '고풍'],
    views: 89,
    likes: 19,
    condition: '최상급',
    certification: true,
    artistId: '8',
  },
  {
    id: '9',
    title: '한자서예 - 초서체 (국전지)',
    titleEn: 'Chinese Calligraphy - Cursive Script (Exhibition Size 70×200cm)',
    titleJa: '漢字書道 - 草書 (国展紙 70×200cm)',
    titleZh: '汉字书法 - 草书 (国展纸 70×200cm)',
    artist: '박초서',
    artistEn: 'Park Cho-seo',
    artistJa: 'パク・チョソ',
    artistZh: '朴草书',
    category: '한자서예',
    style: '전통',
    font: '초서',
    paperSize: '국전지(70×200cm)',
    medium: '한지에 먹',
    mediumEn: 'Ink on Hanji',
    dimensions: '70 × 200 cm',
    year: 2024,
    price: 1200000,
    currency: 'KRW',
    description:
      '국전지 규격(70×200cm)의 대형 초서체 작품입니다. 역동적이고 자유로운 필획이 화면 전체에 펼쳐져 웅장한 기운을 자아냅니다.',
    descriptionEn: 'A large-scale cursive script work in exhibition paper size (70×200cm).',
    descriptionJa: '国展紙規格(70×200cm)の大型草書作品です。',
    descriptionZh: '国展纸规格(70×200cm)的大型草书作品。',
    imageUrl: '/images/artworks/calligraphy-scene-1.jpg',
    images: ['/images/artworks/calligraphy-scene-1.jpg'],
    isAvailable: true,
    isFeatured: true,
    tags: ['한자서예', '초서', '국전지', '대형작품'],
    views: 203,
    likes: 45,
    condition: '최상급',
    certification: true,
    artistId: '9',
  },
]
